### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by sevenoffline** [fgebhart/mapa#49]
This is probably not very important, but it would be nice to have units displayed. For example there's no unit shown on the Z-offset slider. Since this value is directly related to the resulting object's dimensions it would be nice, too to show some information about how large the resulting model will be. 

Typical use case: I want the object to be exactly 1cm thick (base height). I set that and generate the object. In my slicer I notice, the object is too large for my printer and I have to scale it down by 50%. Now my object is only 0.5cm thick. Arrrgh! Back to the website, set the offset to 2cm, re-generate, ...

Dream-solution A: after the rectangle has been drawn, the dimensions are displayed with the possibility to scale them (with locked ratio).
Dream-solution-B: a value can be entered for the largest object-dimension - if it's set to "square" that value will be used for both dimensions.

**Comment by fgebhart** [comment]
That is actually a good catch. Most likely you already have generated more STL files via the streamlit app, than I did 😉 

Mapa provides a feature to specify the desired model (stl file) dimensions aka [model size](https://github.com/fgebhart/mapa/blob/main/mapa/__init__.py#L167). It should be rather straight forward to add another [input widget](https://docs.streamlit.io/library/api-reference/widgets) (again a `st.slider` or `st.number_input` maybe) to the ["customization" section within the sidebar](https://github.com/fgebhart/mapa-streamlit/blob/main/app.py#L165) and pass that value to `convert_bbox_to_stl`. A hint within the tooltips/help that the values are in millimeter should help in making the dimensions transparent. 

Since the web app you are interacting with is based on [streamlit](https://streamlit.io/), the possibilities to what can be implemented are somewhat limited. I do not have the complete freedom of implementing whatever html or javascript what I want. However, using streamlit allows for building data apps super fast, which is why I prefer to keep it that simple.

Because of that, I'd propose to go for dream-slution-B, as described. And as I said, implementing this feature is straight forward, because of that I'd like to ask, if you are willing to give it a try yourself? If yes, I'd add a little section on "development" to the readme and provide support and more details if needed. If not, no worries, I will try to take care of it soon, just let me know.

Keep it going with the great suggestions!

**Comment by fgebhart** [comment]
fyi, just added this brief section on development and contributions: https://github.com/fgebhart/mapa-streamlit/tree/add_dev_section_to_readme#development--contributions

**Comment by sevenoffline** [comment]
:D thanks for the offer (really!) but no. I'm a pro-user by heart and I like it very much to help you with this from the user-perspective. I may have the understanding of how smth should be designed to be easily usable and I may have a intuition of the possibilities/limitations of the coding behind that but I very much lack the micro-logic that is necessary in coding. And baybe that's even better: I'm not burdened by the "how" and you are not burdened too much by the "what".

**Comment by fgebhart** [comment]
Sure, no problem. Anyway, I appreciate your suggestions and feature requests 👍

**Comment by fgebhart** [comment]
It is now possible to specify the desired model size (in millimeter) via the [model size slider](https://github.com/fgebhart/mapa-streamlit/pull/24). With this the impact of z-offset is directly available in millimeter and your described workflow should be simplified.
