### ISSUE TITLE
No update on area change

### ISSUE THREAD

**Issue by sevenoffline** [fgebhart/mapa#56]
I just rectangled an area, generated and exported the stl. I then noticed, that the centered city was way off (that's another issue...) and shifted the rectangle sideways (and saved the change). I then re-generated the stl (it was much faster than the first time) and downloaded the new version - same filesize, strange. I then noticed that it was the exact same model!
Conclusion: the edit-rectangle-tool does not change the generated model, it does not re-generate but takes the previous data.

**Comment by fgebhart** [comment]
Indeed, I verified that issue. Updating a rectangle using the "Edit layers" button does not update the coordinates of the given rectangle. 

The computation in that case is expected to be much faster, since I've implemented a caching mechanism which caches the geotiff to speed up situations where people would only modify the z-scale, offset or model-size.

To me this seems to be an issue with streamlit-folium. Have opened an issue on that library to verify my assumption: https://github.com/randyzwitch/streamlit-folium/issues/41

**Comment by fgebhart** [comment]
Just released v0.6.2 which fixes this issue. With [these changes](https://github.com/fgebhart/mapa-streamlit/pull/29) a modified rectangle now also updates the given output STL file. Turns out it was a rather simple fix on streamlit-folium which in turn required some adaptions on my end.

Happy to receive some feedback.

**Comment by sevenoffline** [comment]
Can confirm, works now! Nice.
