### ISSUE TITLE
ssl issues

### ISSUE THREAD

**Issue by winroger** [fgebhart/mapa#86]
Hello, I am not an expert programmer, but recently having SSL issues using mapa. Could it be that it needs some update here? Thank you! "URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>"

**Comment by fgebhart** [comment]
Hi @winroger 👋 
thanks for bringing this to my attention. Even though the error appeared slightly different on my end [1] I guess it stems from the same root cause. Turns out the planetary computer requires to sign the stac catalogue items. Not sure when this changed, but I implemented the required changes to make it work again. Please try v0.13.0 that I just released and let me know your findings 🙂 

[1] 
```
HTTP Error: Public access is not permitted on this storage account
```
